corpus_id: 173
customer_id: 1526022105

app_title: "Ask HBS"
search_title: "Ask HBS"
search_description: "Harvard Business School"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 10
summary_temp: 0.0
rerank: true
rerank_num_results: 100

enable_summary: false

enable_source_filters: False
source: ""
