corpus_id: 160
customer_id: 1526022105

search_title: "Will Larson Blog Search"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7

enable_source_filters: False
sources: ""

