corpus_id: 169
customer_id: 1526022105

app_title: "Yelp reviews"
search_title: "Ask Yelp"
search_description: "Restaurants in St. Louis"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7
rerank: true
rerank_num_results: 25

enable_source_filters: False
source: ""
