corpus_id: 172
customer_id: 1526022105

app_title: "Ask UCLA"
search_title: "Ask UCLA"
search_description: "About Admissions"

summary_default_language: "en"
summary_num_sentences: 3
summary_num_results: 10
rerank: true

enable_source_filters: False
source: ""
