corpus_id: 148
customer_id: 1526022105

search_title: "Wikipedia top-1K search"

enable_source_filters: False
sources: ""

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7
