corpus_id: 170
customer_id: 1526022105

search_title: "Ask about Transformers"

enable_source_filters: False
sources: ""

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7
