corpus_id: "138,139,140,141,142,150"
customer_id: 1526022105

authenticate: True
google_client_id: "258293899065-0tdl3krtmsccuqcmm5o4pu2d95ufs2cd.apps.googleusercontent.com"

enable_source_filters: True
sources: "website,notion,jira,docusaurus,discourse,github"

summary_default_language: "eng"
summary_num_sentences: 3
summary_num_results: 7

app_title: "Workplace search"
search_title: "Workplace search"
search_logo_src: ""
search_logo_alt: "Workplace Answers logo"
search_logo_height: "49"